const FETCH_USER_DATA = "FETCH_USER_DATA";
const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
const FETCH_USER_DATA_ERROR = "FETCH_USER_DATA_ERROR";
const FETCH_TOKEN = "FETCH_TOKEN";
const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS";
const FETCH_TOKEN_ERROR = "FETCH_TOKEN_ERROR";
const FETCH_REFRESH_TOKEN = "FETCH_REFRESH_TOKEN";
const FETCH_REFRESH_TOKEN_SUCCESS = "FETCH_REFRESH_TOKEN_SUCCESS";
const FETCH_REFRESH_TOKEN_ERROR = "FETCH_REFRESH_TOKEN_ERROR";

export {
  FETCH_REFRESH_TOKEN,
  FETCH_REFRESH_TOKEN_ERROR,
  FETCH_REFRESH_TOKEN_SUCCESS,
  FETCH_TOKEN,
  FETCH_TOKEN_ERROR,
  FETCH_TOKEN_SUCCESS,
  FETCH_USER_DATA,
  FETCH_USER_DATA_ERROR,
  FETCH_USER_DATA_SUCCESS
};
