const FETCHING_PEOPLE = "FETCHING_PEOPLE";
const FETCHING_PEOPLE_SUCCESS = "FETCHING_PEOPLE_SUCCESS";
const FETCHING_PEOPLE_FAILURE = "FETCHING_PEOPLE_FAILURE";
const EMPTY_PEOPLE = "EMPTY_PEOPLE";

export {
  FETCHING_PEOPLE,
  FETCHING_PEOPLE_FAILURE,
  FETCHING_PEOPLE_SUCCESS,
  EMPTY_PEOPLE
};
