const LOGGED_IN = "LOGGED_IN";
const LOGIN = "LOGIN";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT = "LOGOUT";

export { LOGGED_IN, LOGIN, LOGIN_ERROR, LOGIN_SUCCESS, LOGOUT };
