const TRANSACTION = "TRANSACTION";
const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
const TRANSACTION_ERROR = "TRANSACTION_ERROR";
const FETCH_HISTORY = "FETCH_HISTORY";
const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
const FETCH_HISTORY_ERROR = "FETCH_HISTORY_ERROR";
const FETCH_SOLDE = "FETCH_SOLDE";
const FETCH_SOLDE_SUCCESS = "FETCH_SOLDE_SUCCESS";
const FETCH_SOLDE_ERROR = "FETCH_SOLDE_ERROR";

export {
  TRANSACTION,
  TRANSACTION_ERROR,
  TRANSACTION_SUCCESS,
  FETCH_HISTORY,
  FETCH_HISTORY_ERROR,
  FETCH_HISTORY_SUCCESS,
  FETCH_SOLDE,
  FETCH_SOLDE_ERROR,
  FETCH_SOLDE_SUCCESS
};
