import { StyleSheet } from "react-native";

export default {
  name: [
    "Aina",
    "Ainga",
    "Aintsoa",
    "Ando",
    "Andry",
    "Andy",
    "Anja",
    "Antsa",
    "Antso",
    "Avo",
    "Bako",
    "Bakoly",
    "Baliaka",
    "Baovola",
    "Benja",
    "Dadavy",
    "Dama",
    "Dimby",
    "Dina",
    "Elintsoa",
    "Faly",
    "Fanja",
    "Fidy",
    "Haingo",
    "Hanta",
    "Harena",
    "Hasina",
    "Harizo",
    "Henintsoa",
    "Ialy",
    "Iony",
    "Joda",
    "Kiady",
    "Mamy",
    "Tovo",
    "Toky",
    "Mandresy",
    "Miora",
    "Mamy",
    "Mbola"
  ],
  client_id: "ariarynet",
  client_secret: "ariarynetpass",
  ARIARY_BASE_URL: "http://54.229.79.45/ariary2API/web/api/",
  BASE_URL: "http://ariary.vola.mg/",
  NEW_BASE_URL: "http://ariary.vola.mg/new_serv/",
  BASE_URL_Oauth: "http://auth.vola.mg/",
  redirect_uri: "http://auth.vola.mg/index.php/",
  scope: "userinfo",
  grant_type_Oauth: "authorization_code",
  grant_type_refresh: "refresh_token",
  client_id : 'ariarynet',
  client_secret : 'ariarynetpass',
  uri:
    "http://auth.vola.mg/oauth2/authorize?response_type=code&state=xyz&client_id=ariarynet&redirect_uri=http://auth.vola.mg/index.php/&scope=userinfo",
  message: [
    "Prenez en photo avec l'application AriaryClient pour recevoir de l'argent",
    "Ariary.net, la solution de paiement simple, rapide, efficace et sécurisée",
    "L'argent reçu sera versé directement vers le compte principal",
    "Partager votre identifiant à vos proches via d'autres applications",
    "Consulter directement votre historique directement via le bouton en haut"
  ]
};
